org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

modVersion=26.1.2-3.0.0
modid=rsinsertexportupgrade
currentChangelog=- 26.1.2 Port

refinedarchitectVersion=1.7.1
refinedstorageVersion=3.2.1
refinedstorageQuartzArsenalVersion=2.0.6
curiosVersion=15.0.0+26.1.2
mekanismVersion=
jeiVersion=29.5.0.24
minecraftVersion=26.1.2