org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

modVersion=1.21.1-2.1.2
modid=rsinsertexportupgrade
currentChangelog=- Renamed to Refined Wireless Upgrades!\n- Addon developers can now register own wireless grid upgrades easily (For more information, visit: https://github.com/starforcraft/Refined-Wireless-Upgrades/tree/1.21.1/docs/addon-upgrades.md)\n- Increased default wireless grid upgrade slots to 4\n- Added magnet upgrade\n- Added energy capacity card\n- Added liquid, chemical and energy support\n- Added curios compat\n- Charging the wireless grid itself is now possible

refinedarchitectVersion=1.4.1
refinedstorageVersion=2.0.9
refinedstorageQuartzArsenalVersion=1.0.8
curiosVersion=9.5.1+1.21.1
mekanismVersion=10.7.19.85
grandpowerVersion=3.0.2
jeiVersion=19.39.0.371
minecraftVersion=1.21.1
neoforge_version=21.1.249