org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

modVersion=1.21.1-2.1.1
modid=rsinsertexportupgrade
currentChangelog=- Fixed any upgrade not working inside a Wireless Crafting Grid or a Wireless Universal Grid\n- Fixed any upgrade not working when installed in any Grid inside a Curios slot

refinedarchitectVersion=1.4.1
refinedstorageVersion=2.0.9
refinedstorageQuartzArsenalVersion=1.0.8
jeiVersion=19.39.0.371
minecraftVersion=1.21.1
neoforge_version=21.1.249