modLoader="javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/starforcraft/Refined-Wireless-Upgrades/issues/new/choose"
license="MIT"
[[mods]]
modId="rsinsertexportupgrade"
version = "${version}"
displayName="Refined Wireless Upgrades"
displayURL="https://www.curseforge.com/minecraft/mc-mods/refined-wireless-upgrades"
logoFile="logo.png"
authors="Ultramega"
description="Adds various upgrade cards which can be installed into any Wireless Grid."

[[mixins]]
config="rsinsertexportupgrade.mixins.json"

[[dependencies.rsinsertexportupgrade]]
modId="refinedstorage"
type="required"
versionRange="[3.2.1,4)"
ordering="NONE"
side="BOTH"

[[dependencies.rsinsertexportupgrade]]
modId="minecraft"
type="required"
versionRange="[26.1.2,26.2)"
ordering="NONE"
side="BOTH"

[[dependencies.rsinsertexportupgrade]]
modId="curios"
type="optional"
versionRange="[15,16)"
ordering="AFTER"
side="BOTH"
