modLoader="javafml"
loaderVersion = "[2,)"
issueTrackerURL="https://github.com/starforcraft/RS-Insert-Export-Upgrade/issues/new/choose"
license="MIT"
[[mods]]
modId="rsinsertexportupgrade"
version = "${version}"
displayName="RS Insert Export Upgrade"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rs-insert-export-upgrade"
logoFile="logo.png"
authors="Ultramega"
description="Adds an Insert and Export Upgrade which can be installed into any Wireless Grid."

[[mixins]]
config="rsinsertexportupgrade.mixins.json"

[[dependencies.rsinsertexportupgrade]]
modId="refinedstorage"
type="required"
versionRange="[2.0.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.rsinsertexportupgrade]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"
